-- ----------------------------------------------------------------------------
-- Put here INSERT statements for inserting data required by the application
-- in the "pojo" database.
-------------------------------------------------------------------------------

INSERT INTO Province VALUES(1, 'A Coruña');
INSERT INTO Province VALUES(2, 'Lugo');
INSERT INTO Province VALUES(3, 'Ourense');
INSERT INTO Province VALUES(4, 'Pontevedra');

INSERT INTO Cinema VALUES(1, 'Espacio Coruña', 6, 1);
INSERT INTO Cinema VALUES(2, 'Los Rosales', 6, 1);
INSERT INTO Cinema VALUES(3, 'Marineda', 6, 1);
INSERT INTO Cinema VALUES(4, 'Cinesa Lugo', 6, 2);
INSERT INTO Cinema VALUES(5, 'Cinesa Ourense', 7, 3);

INSERT INTO Room VALUES(null, 'Sala 1', 100, 1);
INSERT INTO Room VALUES(null, 'Sala 2', 100, 1);
INSERT INTO Room VALUES(null, 'Sala 3', 100, 1);
INSERT INTO Room VALUES(null, 'Sala 1', 100, 2);
INSERT INTO Room VALUES(null, 'Sala 2', 100, 2);
INSERT INTO Room VALUES(null, 'Sala 3', 100, 2);
INSERT INTO Room VALUES(null, 'Sala 1', 100, 3);
INSERT INTO Room VALUES(null, 'Sala 2', 100, 3);
INSERT INTO Room VALUES(null, 'Sala 1', 100, 4);
INSERT INTO Room VALUES(null, 'Sala 2', 100, 4);

INSERT INTO Movie VALUES(null, '12 años de esclavitud', 'Descripción de 12 años de exclavitud', 133, '2014-01-01', '2015-01-01');
INSERT INTO Movie VALUES(null, 'Gravity', 'Descripción de Gravity', 90, '2014-01-01', '2015-01-01');
INSERT INTO Movie VALUES(null, 'El lobo de Wall Street', 'Descripción de El lobo de Wall Street', 180, '2014-01-01', '2015-01-01');
INSERT INTO Movie VALUES(null, 'American Hustle', 'Descripción de American Hustle', 138, '2014-01-01', '2015-01-01');
INSERT INTO Movie VALUES(null, 'Her', 'Descripción de Her', 126, '2014-01-01', '2015-01-01');
INSERT INTO Movie VALUES(null, 'Capitán Phillips', 'Descripción de Capitán Phillips', 135, '2014-01-01', '2015-01-01');

INSERT INTO UserProfile VALUES(null, 'admin', '12345678A', 'IT2WiV6Lf7YNE', 'admin', '', '', 'admin');
INSERT INTO UserProfile VALUES(null, 'taquillero', '12345678B', 'IT2WiV6Lf7YNE', 'taquillero', 'lastname 1', 'user1@user.com', 'salesman');
INSERT INTO UserProfile VALUES(null, 'user', '12345678Z', 'IT2WiV6Lf7YNE', 'User', 'Profile', 'user@user.com', null);
INSERT INTO UserProfile VALUES(null, 'ana', '12345678C', 'IT2WiV6Lf7YNE', 'Ana', 'Perez', 'ana@user.com', null);
INSERT INTO UserProfile VALUES(null, 'carlos', '12345678D', 'IT2WiV6Lf7YNE', 'Carlos', 'Rodriguez', 'carlos@user.com', null);
INSERT INTO UserProfile VALUES(null, 'nestor', '12345678E', 'IT2WiV6Lf7YNE', 'Néstor', 'Ortiz', 'nestor@user.com', null);

-- Sesiones: id, fecha, sitios, precio, sala, película, versión.
-- Hoy:
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 10, TIMESTAMPADD(MINUTE, 00, CURDATE())), 20, 6, 1, 5, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 10, TIMESTAMPADD(MINUTE, 30, CURDATE())), 20, 6, 2, 6, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE())), 20, 6, 1, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 18, TIMESTAMPADD(MINUTE, 30, CURDATE())), 20, 6, 1, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 00, CURDATE())), 20, 6, 1, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 23, TIMESTAMPADD(MINUTE, 30, CURDATE())), 20, 6, 3, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 17, TIMESTAMPADD(MINUTE, 00, CURDATE())), 20, 6, 3, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE())), 20, 6, 2, 2, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 17, TIMESTAMPADD(MINUTE, 30, CURDATE())), 20, 6, 2, 3, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(HOUR, 19, TIMESTAMPADD(MINUTE, 30, CURDATE())), 20, 6, 2, 3, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 1, TIMESTAMPADD(HOUR, 00, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 1, 0);

-- Mañana (a la primera sesión solo le quedan 8 entradas disponibles).
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 1, TIMESTAMPADD(HOUR, 13, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 8, 6, 1, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 1, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 5, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 1, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 3, 3, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 1, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 1, TIMESTAMPADD(HOUR, 21, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 5, 0);

-- +2
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 2, TIMESTAMPADD(HOUR, 13, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 1, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 2, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 2, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 2, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 2, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 2, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 2, TIMESTAMPADD(HOUR, 21, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 6, 0);

-- +3
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 3, TIMESTAMPADD(HOUR, 13, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 6, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 3, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 2, 2, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 3, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 1, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 3, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 3, TIMESTAMPADD(HOUR, 21, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 5, 0);

-- +4
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 4, TIMESTAMPADD(HOUR, 13, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 6, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 4, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 3, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 4, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 4, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 5, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 4, TIMESTAMPADD(HOUR, 21, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 5, 0);

-- +5
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 5, TIMESTAMPADD(HOUR, 13, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 6, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 5, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 2, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 5, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 5, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 5, TIMESTAMPADD(HOUR, 21, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 5, 0);

-- +6
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 6, TIMESTAMPADD(HOUR, 13, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 6, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 6, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 3, 3, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 6, TIMESTAMPADD(HOUR, 16, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 1, 4, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 6, TIMESTAMPADD(HOUR, 20, TIMESTAMPADD(MINUTE, 30, CURDATE()))), 20, 6, 1, 5, 0);
INSERT INTO SessionMovie VALUES(null, TIMESTAMPADD(DAY, 6, TIMESTAMPADD(HOUR, 21, TIMESTAMPADD(MINUTE, 00, CURDATE()))), 20, 6, 2, 5, 0);


-- Compras: id, tickets, entregada, numero de tarjeta, fecha de caducidad, fecha de compra, id de sesion, id de usuario.
INSERT INTO Buy VALUES(null, 5, false, '1111111111111111', TIMESTAMPADD(DAY, 30, CURDATE()), NOW(), 13, 3);
INSERT INTO Buy VALUES(null, 5, false, '1111111111111111', TIMESTAMPADD(DAY, 30, CURDATE()), NOW(), 13, 3);
INSERT INTO Buy VALUES(null, 5, false, '1111111111111111', TIMESTAMPADD(DAY, 30, CURDATE()), NOW(), 13, 3);
INSERT INTO Buy VALUES(null, 5, false, '1111111111111111', TIMESTAMPADD(DAY, 30, CURDATE()), NOW(), 14, 3);
INSERT INTO Buy VALUES(null, 5, false, '1111111111111111', TIMESTAMPADD(DAY, 30, CURDATE()), NOW(), 14, 3);
INSERT INTO Buy VALUES(null, 5, false, '1111111111111111', TIMESTAMPADD(DAY, 30, CURDATE()), NOW(), 14, 3);



